version: '3.8'

services:
  postgres:
    container_name: db-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres" 
    ports:
      - "4321:5432" 

  # node:
  #   build: ./
  #   container_name: nest-js-backend
  #   depends_on:
  #     - postgres

